# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\demo.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").variables(
        **{"memberId":"${memberId}",
           "host":"mubu.com",
           "phone":"",
           "password":"",
           "title":""})
        .verify(False)
        .export("title","docID")

    teststeps = [

        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "4a5a2fde-fdde-45fb-8fdb-2b19e120aba8",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id","docID")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "a74fe415-36c8-446f-ba8b-b5e49978d936",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "37fb15e4-7777-4876-8b9d-57e253eb3d06",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"document_id": "jGADEOIbyW"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "36",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "949ea2f8-2192-4a8b-9b01-7a9e43f851bb",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"docId": "jGADEOIbyW", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "e75239da-b029-45f9-9209-5ce44020b8b5",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"targetDocId": "jGADEOIbyW"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .with_variables(**{"remeber":True})
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "x-request-id": "66d0c60c-6b3b-4a8c-be12-cd9039327c80",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)

        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "${memberId}", "documentId": "jGADEOIbyW"})
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "${memberId}", "documentId": "jGADEOIbyW"})
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "members:${memberId}:1613450272086",
                    "x-request-id": "b7de449e-4170-4c0a-bded-4915a164e77a",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.data.next","/next")
            .assert_length_greater_than("$folderList",5)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:3",
                    "x-request-id": "4a6f7e74-bc9b-4140-971c-ac5965493b73",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:11023082:${memberId}:3",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "d", "original": ""},
                                {"name": "nameChanged", "title": "de", "original": "d"},
                                {
                                    "name": "nameChanged",
                                    "title": "dem",
                                    "original": "de",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "361",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:5",
                    "x-request-id": "905cf160-6d09-4a23-b0c4-8f354e3a45c4",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:11023082:${memberId}:5",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 1,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "demo",
                                    "original": "dem",
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "edd320a4-51ae-4854-acb3-462a9d2d241d",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"docId": "jGADEOIbyW", "keywords": "demo", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "657",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:6",
                    "x-request-id": "bb72eff0-9b97-4ac9-979d-a44e543843b0",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 6,
                    "requestId": "MESSAGE:11023082:${memberId}:6",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 2,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "EgIYL4Sk8y",
                                                "text": "",
                                                "modified": 1613450276761,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "EgIYL4Sk8y",
                                                "text": "<span>111</span>",
                                                "modified": 1613450277209,
                                            },
                                            "original": {
                                                "id": "EgIYL4Sk8y",
                                                "text": "",
                                                "modified": 1613450276761,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "459",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:8",
                    "x-request-id": "000d063b-e85d-4aa7-a3ed-5b209c9fd123",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 8,
                    "requestId": "MESSAGE:11023082:${memberId}:8",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "01WDWjqJQw",
                                                "text": "",
                                                "modified": 1613450278275,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "505",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:10",
                    "x-request-id": "f49e5548-f5da-4e9a-ad5d-9a2745690593",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 10,
                    "requestId": "MESSAGE:11023082:${memberId}:10",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "01WDWjqJQw",
                                                "text": "<span>22</span>",
                                                "modified": 1613450279345,
                                            },
                                            "original": {
                                                "id": "01WDWjqJQw",
                                                "text": "",
                                                "modified": 1613450278275,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "521",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:12",
                    "x-request-id": "9a72729b-77c6-4c35-9bee-25597cb166b9",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 12,
                    "requestId": "MESSAGE:11023082:${memberId}:12",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "01WDWjqJQw",
                                                "text": "<span>222</span>",
                                                "modified": 1613450279538,
                                            },
                                            "original": {
                                                "id": "01WDWjqJQw",
                                                "text": "<span>22</span>",
                                                "modified": 1613450279345,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "461",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "${memberId}",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "request-id": "MESSAGE:11023082:${memberId}:13",
                    "x-request-id": "bf8fd16f-fb78-4fba-a16d-7cd526abb5af",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:11023082:${memberId}:13",
                    "token": "jGADEOIbyW",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "jGADEOIbyW",
                            "version": 6,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 2,
                                            "parentId": None,
                                            "node": {
                                                "id": "TwBJBvpaOd",
                                                "text": "",
                                                "modified": 1613450294257,
                                                "children": [],
                                            },
                                            "path": ["nodes", 2],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 10.0",
                        "appVersion": "2.0.0.846",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "74e7194a-7757-45c7-80e5-437a8f2deab6",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36",
                    "data-unique-id": "d99ac5d6-6e0b-475a-adec-73238119db21",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEwMjMwODIiLCJleHAiOjE2MTYwNDIyNjIsImlhdCI6MTYxMzQ1MDI2Mn0.ZFueluxBUgSkL9uzXJMgHWS-Ixt2m7SoY6HONZ-AAl0DiBAqFZRF-cSwF0VS3HEfdZkfFxdv7jHEGgusU4uNaA",
                    "x-request-id": "99ceb562-495c-42a9-a909-bf827d77d6b2",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh-TW;q=0.9,zh;q=0.8,en-US;q=0.7,en;q=0.6",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
